sudo: required

language: generic

env:
  - PYGMY_VM_USER=$USER

before_install:
  - chmod ug+x ./provision.sh

script:
  - ./provision.sh
  # Re-provision to test for idempotency.
  - ./provision.sh
  - pygmy up
